using System;
using Xamarin.Forms;

namespace RightPath.Views
{
	public partial class EULAPage : ContentPage
	{
		public EULAPage()
		{
			InitializeComponent();

			var htmlSource = new HtmlWebViewSource();
			htmlSource.Html = @"<p>MOBILE APP END USER LICENSE AGREEMENT</p>
<p>Effective Date July 25, 2016</p>
<p>THE APPLICATION (AS DEFINED BELOW) YOU ARE DOWNLOADING OR HAVE DOWNLOADED HAS BEEN PROVIDED BY Turnkey Estimates, LLC OR ITS AFFILIATES (COLLECTIVELY, ""Turnkey Estimates"" or ""we""). BY INSTALLING OR USING ALL OR ANY PORTION OF THE APPLICATION, YOU ACCEPT ALL THE TERMS AND CONDITIONS OF THIS END USER LICENSE AGREEMENT (""AGREEMENT""). UPON ACCEPTANCE, THIS AGREEMENT IS ENFORCEABLE AGAINST YOU AND ANY ENTITY OR THIRD PARTY USER THAT OBTAINED THE APPLICATION AND ON WHOSE BEHALF IT IS USED. IF YOU DO NOT ACCEPT THE TERMS AND CONDITIONS OF THIS AGREEMENT, DO NOT INSTALL OR USE THE APPLICATION. ACCORDINGLY, YOU AND Turnkey Estimates AGREE TO THE FOLLOWING:</p>
<p>The ""Application"" consists of: (a) the Turnkey Estimates<sup>&copy;</sup> mobile application provided in connection with an authorized link to this Agreement, including all software, code, text, graphics, logos, layouts, designs, interfaces, and other items included in or associated with the application; and (b) any files that are delivered to you by Turnkey Estimates (via online transmission, through a third party distributor, or otherwise) to patch, update, or otherwise modify the Turnkey Estimates<sup>&copy;</sup> mobile application.</p>
<p>The Application may provide a means for you to access one or more websites, other applications, or other products and services offered by Turnkey Estimates (collectively, the ""Services""), and audio and video materials, photographs, text, graphics, logos, layouts, designs, interfaces, software, data and other content associated with the Services (""Content""). The Application, Services and Content are copyrighted works of Turnkey Estimates and may contain trademarks, service marks, trade names, and other intellectual property of Turnkey Estimates.</p>
<p>The Application and Content, and your use of the Services, are also subject to Turnkey Estimates' Terms of Use, Privacy Policy and Video Services and Social Networking Policy (collectively ""Turnkey Estimates Terms"") which are incorporated into this Agreement by this reference. There may also be additional terms that Turnkey Estimates presents to you in connection with the Application, for example, at the time of download (""Additional Terms""). If there is a conflict between this Agreement and any Additional Terms, the Additional Terms will control unless the Additional Terms expressly provide otherwise.</p>
<p>If you are obtaining the Application from a distribution channel such as the Apple App Store or the Android Marketplace (""Distribution Channel""), your purchase, if the application is paid, may be subject to additional terms of the Distribution Channel. This Agreement is between you and us only, and not with the Distribution Channel. We, rather than the Distribution Channel, are responsible for the Application and the content thereof. Neither we nor the Distribution Channel has any obligation to furnish any maintenance and support services with respect to the Application.</p>
<p>The Application may use location-based services to locate you. If you choose to use the Application, you consent to Turnkey Estimates and its third party providers determining your location.</p>
<ol>
<li><strong> Changes to this Agreement and Turnkey Estimates Terms.</strong></li>
</ol>
<p>This Agreement applies to all downloading or installation of the Application after the Effective Date above, and use of any copy of the Application downloaded or installed after the Effective Date above. Turnkey Estimates may make changes to this Agreement from time to time by posting a copy of the updated Agreement at www.rightpathrealestate.com or incorporated in software updates to this application subsequent to your download or installation of this application. Changes to this Agreement will be applicable to downloading or installation of the Application after the effective date of the changes. If you do not agree with any changes to this Agreement, your sole remedy is not to download or install the Application or uninstall or remove the application after the effective date of the changes.</p>
<p>Turnkey Estimates also may make changes to the Turnkey Estimates Terms as provided therein. Such changes will apply to your use of the Application to access Services and Content after the effective date of the changes. If you do not agree with any such changes, your sole remedy is to discontinue use of the Application to access the relevant Services and Content. If you continue to use the Application to access Services and Content after the effective date of the changes, you accept all changes.</p>
<ol start=""2"">
<li><strong> Changes to Product and Service Offerings.</strong></li>
</ol>
<p>Turnkey Estimates or the Distribution Channel may change pricing for the Application, Services and Content. We may not provide price protection or refunds due to price reductions, promotional pricing, or any other changes to pricing for any reason.</p>
<p>You acknowledge and agree that Turnkey Estimates may suspend or discontinue offering the Application; modify the Application; change or discontinue the Services available through the Application; change how we offer and operate such Services (e.g., to begin charging a fee to access features or Content that we previously made available without charge); remove Content; impose limits on certain features or restrict your access to part or all of the Application, Services and Content; or make other changes in Turnkey Estimates' product and service offerings at its sole discretion and with or without notice to you. We will not be liable to you or any third party for taking any of these actions and we will not be limited to the remedies above if you violate these Turnkey Estimates Terms. You further acknowledge and agree that even if a copy of the Application continues to reside on your device, after we make changes in our product or services offerings, the Application may not work as it did prior to such action, and Turnkey Estimates will have no liability to you or any third party as a result.</p>
<ol start=""3"">
<li><strong> Ownership.</strong></li>
</ol>
<p>You acknowledge and agree that Turnkey Estimates has all right, title, and interest in and to the Application and all intellectual property rights associated with the Application. The Application is protected by the copyright laws of the United States, international treaties and conventions, and other laws. Except as expressly stated herein, you have no intellectual property rights in the Application (including without limitation any rights to use the trademarks, trade names, service marks, logos, domain names, and other distinctive brand features), and Turnkey Estimates reserves all rights not expressly granted to you. You must comply with all laws when using the Application as well as all applicable copyright, trademark or other legal notices or restrictions.</p>
<p>You will not:</p>
<p>in whole or in part, copy, reproduce, translate, modify, adapt, create derivative works based on, or reverse engineer, derive source code from, disassemble, decompile, or otherwise attempt to discover the source code of, the Application, except to the extent required by applicable law;</p>
<p>install or use the Application on a computer or other device that is primarily used as a file server;</p>
<p>remove, obscure, or alter any copyright, trademark, logo, or other proprietary notices in or on the Application;</p>
<p>use any unauthorized third-party software that intercepts, ""mines,"" or otherwise collects information from or through the Application, unless authorized by Turnkey Estimates in its sole discretion;</p>
<p>distribute, publish, display, perform, sell, rent, lease, sublicense, assign, transfer, or grant a security interest in your rights in the Application, or authorize all or any portion of the Application to be copied onto another user's computer except as permitted hereunder;</p>
<p>intercept, emulate, or redirect the communication protocols used by the Application in any way, for any purpose, or engage in any activity that interferes with or disrupts the Application or Turnkey Estimates' or its vendors' servers or other infrastructure; or</p>
<p>facilitate, create, or maintain any unauthorized connection to the Application, including without limitation: (a) any connection to any unauthorized server that emulates, or attempts to emulate, Turnkey Estimates' or its vendors' servers; and (b) any connection using programs or tools not approved by Turnkey Estimates in its sole discretion.</p>
<p>The Services and Content accessible through the Application are also protected by intellectual property and other laws in the U.S. and in other countries, and are subject to limitations on your use thereof, as set forth more fully in the Turnkey Estimates Terms.</p>
<ol start=""4"">
<li><strong> Grant of a Limited Use License</strong>.</li>
</ol>
<p>Subject to your compliance with the Turnkey Estimates Terms and this Agreement, Turnkey Estimates hereby grants, and you hereby accept, a limited, non-exclusive license to: (a) install the Application on one mobile device owned by you or under your legitimate control; and (b) engage in non-commercial use of the Application. All rights to use the Application are granted on the condition that such rights are forfeited if you fail to comply with the terms of this Agreement.</p>
<ol start=""5"">
<li><strong> Use of the Application</strong>.</li>
</ol>
<p>When you use the Application, you may connect to Turnkey Estimates' or its vendors' servers. You consent to our use of data that you provide through the Application. Turnkey Estimates will not store any personal information about you.&nbsp;</p>
<p>The Application may allow you to access and interoperate with third party properties, software applications, and data services (collectively, ""Third Party Properties""). Turnkey Estimates does not control any Third Party Properties to which you may connect using the Application and is not responsible for the practices of any third party. You acknowledge and agree that Turnkey Estimates is not liable for any loss or damage which may be incurred by you as a result of any reliance placed by you on the completeness, accuracy, or existence of any advertising, products, or other materials on or available from Third Party Properties. You acknowledge that the Application may check for updates to the Application that may be available to you.</p>
<ol start=""6"">
<li><strong> Warranty Disclaimer</strong></li>
</ol>
<p>Turnkey Estimates DOES NOT WARRANT: (1) THAT THE APPLICATION'S FUNCTIONS OR ANY SERVICES OR CONTENT WILL BE UNINTERRUPTED OR FREE OF ERRORS OR OMISSIONS; (2) THAT DEFECTS WILL BE CORRECTED; (3) THAT THE APPLICATION OR THE SERVERS HOSTING CONTENT ARE FREE OF VIRUSES OR OTHER HARMFUL CODE; OR (4) THAT THE APPLICATION OR SERVICES OR CONTENT AVAILABLE THROUGH THE APPLICATION WILL CONTINUE TO BE AVAILABLE. Turnkey Estimates SHALL HAVE NO LIABILITY FOR ANY SUCH ISSUES. Turnkey Estimates AND THE DISTRIBUTION CHANNEL DISCLAIM ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, NONINFRINGEMENT, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUALITY, AVAILABILITY AND AS TO SUBJECT MATTER OF CONTENT. THE APPLICATION, SERVICES AND CONTENT ARE PROVIDED ""AS IS,"" ""AS AVAILABLE,"" AND ""WITH ALL FAULTS.""</p>
<p><span style=""text-decoration: underline;""><strong>YOUR ACCESS TO AND USE OF THE APPLICATION IS AT YOUR RISK. THE FUNCTION, OPERATION, AND RESULTS OF THE DATA YOU INPUT IS STRICTLY FOR ESTIMATE AND GENERAL INFORMATIONAL PURPOSES. THIS APPLICATION IS SPECIFICALLY LIMITED FOR USE AS A BROAD ESTIMATION TOOL AND NOT TO BE RELIED UPON BY YOU OR ANY OTHER PARTY FOR ANY PROPERTY INVESTMENT. USE THIS APPLICATION AT YOUR OWN RISK. Turnkey Estimates DOES NOT WARRANT AND EXPRESSLY DISCLAIMS ANY RESULT YOU MAY RECEIVE WHEN USING THIS APPLICATION. ANY INVESTMENT DECISIONS MADE USING THE INFORMATION OR ESTIMATES PROVIDED BY THIS APPLICATION ARE MADE STRICTLY AT YOUR OWN RISK. ANY PROPERTY INVESTMENT DECISION SHOULD BE MADE WITH DUE DILIGENCE ON YOUR PART AND Turnkey Estimates BEARS NO RESPONSIBILITY OR LIABILITY AS TO THE OUTCOME OF ANY INVESTMENT DECISION YOU MAKE. ALWAYS EMPLOY OR CONSULT WITH QUALIFIED AND/OR CERTIFIED INDIVIDUALS OR COMPANIES WHO CAN PROPERLY ADVISE YOU ON THE RISKS ASSOCIATED WITH PROPERTY INVESTMENT OR ANY DAMAGE REPAIR. IF YOU ARE DISSATISFIED WITH THE APPLICATION OR ANY OF THE SERVICES OR CONTENT AVAILABLE THROUGH THE APPLICATION, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND USING THE APPLICATION.</strong></span></p>
<p>The Distribution Channel will not be responsible for addressing any claims by you or any third party relating to the Application or your possession and/or use of the Application, including: (i) product liability claims; (ii) any claim that the Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation. If you have any questions on those issues, you should contact us at the address below. The Distribution Channel will also not be responsible for investigation, defense, settlement and discharge of any third party intellectual property infringement claim.</p>
<ol start=""7"">
<li><strong> Limitation of Liability/Release of Claims</strong></li>
</ol>
<p>Turnkey Estimates WILL NOT BE LIABLE FOR ANY FAILURE OR DELAY IN THEIR PERFORMANCE DUE TO ANY CAUSE BEYOND THEIR REASONABLE CONTROL, INCLUDING ACTS OF WAR, ACTS OF GOD, ACTS OF THIRD PARTY SERVICE PROVIDERS, EARTHQUAKE, FLOOD, EMBARGO, RIOT, SABOTAGE, LABOR SHORTAGE OR DISPUTE, GOVERNMENTAL ACT, POWER FAILURE OR FAILURE OF THE INTERNET OR COMPUTER EQUIPMENT.</p>
<p>Turnkey Estimates WILL NOT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES IN CONNECTION WITH THE APPLICATION (INCLUDING THE SERVICES AND CONTENT AVAILABLE THROUGH THE APPLICATION) OR THIS AGREEMENT, EVEN IF FORESEEABLE OR EVEN IF Turnkey Estimates HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES (INCLUDING, WITHOUT LIMITATION, WHETHER CAUSED IN WHOLE OR IN PART BY NEGLIGENCE, GROSS NEGLIGENCE, OR OTHERWISE, BUT EXCLUDING WILLFUL MISCONDUCT). IN NO EVENT WILL Turnkey Estimates' LIABILITY FOR OTHER DAMAGES EXCEED THE AMOUNT PAID BY YOU TO ACQUIRE THE APPLICATION. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF ANY STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
<p>YOU ACKNOWLEDGE AND AGREE THAT IF YOU INCUR ANY DAMAGES THAT ARISE OUT OF Turnkey Estimates' ACTS OR OMISSIONS, THE DAMAGES, IF ANY, ARE NOT IRREPARABLE AND ARE NOT SUFFICIENT TO ENTITLE YOU TO AN INJUNCTION OR OTHER EQUITABLE RELIEF RESTRICTING EXPLOITATION OF ANY WEBSITE, PROPERTY, PRODUCT, PROGRAM, TELEVISION SHOW, MOTION PICTURE, OR OTHER AUDIO/VISUAL CONTENT OWNED, CONTROLLED, OR DISTRIBUTED BY Turnkey Estimates, INCLUDING WITHOUT LIMITATION THE APPLICATION.</p>
<p>SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OF THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
<ol start=""8"">
<li><strong> Indemnity</strong></li>
</ol>
<p>You will indemnify, defend, and hold Turnkey Estimates and all of its officers, directors, owners, employees, agents, information providers, service providers, vendors, contractors, affiliates, partners, and licensors (collectively, the ""Turnkey Estimates Parties"") harmless from and against any and all liability, losses, costs, and expenses (including attorneys' fees) incurred by any of the Turnkey Estimates Parties in connection with any claim, including, but not limited to, claims for defamation, violation of rights of publicity or privacy, copyright infringement, or trademark infringement arising out of: your use of the Application; any use or alleged use of your account or your passwords by any person, whether or not authorized by you; your connection to Turnkey Estimates' or its vendors' servers; your violation of this Agreement; or your violation of the rights of any other person or entity. Turnkey Estimates reserves the right, at its own expense, to assume the exclusive defense and control of any matter for which you are required to indemnify Turnkey Estimates, and you will cooperate with Turnkey Estimates' defense of these claims.</p>
<ol start=""9"">
<li><strong> Termination.</strong></li>
</ol>
<p>This Agreement is effective until terminated. You may terminate this Agreement at any time by: (i) irretrievably erasing, deleting, or destroying all copies of the Application in your possession or control; and (ii) ceasing to use the Services and Content available through the Application. Turnkey Estimates may terminate this Agreement at any time for any reason or no reason. Upon termination for any reason, the license granted in Section 4 will immediately terminate. The provisions in Sections 1, 2, 3, 5, 6, 7, 8, 11, 12, and 13 will survive any termination.</p>
<ol start=""10"">
<li><strong> Export Controls.</strong></li>
</ol>
<p>You will not ship, transfer, or export the Application into any country or use the Application in any manner prohibited by the United States Export Administration Act or any other export laws, restrictions, or regulations (collectively, ""Export Laws""). You represent and warrant that you are not a citizen of, and are not located within, a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a ""terrorist supporting"" country, and that you are not otherwise prohibited under the Export Laws from receiving the Application.</p>
<ol start=""11"">
<li><strong> Governing Law, Venue, and Jurisdiction.</strong></li>
</ol>
<p>This Agreement and all claims arising from or related to your use of the Application will be governed by and construed in accordance with the laws of the State of Texas, except Texas&rsquo;s conflict of law rules. This Agreement and the Application will not be governed by the United Nations Convention on Contracts for the International Sale of Goods, if applicable.</p>
<p>With respect to any disputes or claims not subject to arbitration (as set forth below), you agree to exclusive jurisdiction in the state and federal courts in Houston, Texas. Notwithstanding any other provision of this Agreement, we may seek injunctive or other equitable relief from any court of competent jurisdiction.</p>
<p>Regardless of any statute or law to the contrary, you must file any claim or action related to use of the Application or this Agreement within one year after such claim or action accrued. Otherwise, you will waive the claim or action.</p>
<ol start=""12"">
<li><strong> Disputes; Arbitration</strong></li>
</ol>
<p>If you have any dispute with or claim against us or any of our affiliates (a ""Claim"") arising out of or relating to the Application or this Agreement, and the claim is not resolved by calling our customer service department at <a href=""mailto:support@rightpathrealestate.com"">support@rightpathrealestate.com</a>, you and we each agree to resolve such disputes through an individual action in small claims court, in the agreed to venue and jurisdiction herein. You and we are each waiving the right to a trial by jury or to participate in a class action. This Section 12 shall survive termination of this Agreement or any subscription that you may have to receive Content. Costs incurred through claims filed in small claims court shall be borne by the party that incurs them.</p>
<ol start=""13"">
<li><strong> Miscellaneous.</strong></li>
</ol>
<p>This Agreement constitutes the entire agreement between the parties with respect to its subject matter and supersedes any prior oral or written agreements, provided, however, that this Agreement will coexist with the Turnkey Estimates Terms and any Additional Terms. To the extent that the provisions of this Agreement conflict with the Turnkey Estimates Terms, this Agreement will govern. We may be required by state or federal law to notify you of certain events. You hereby acknowledge and agree that such notices will be effective upon our posting them on our sites or delivering them to you via email, if you have provided it to us. If you do not provide us with accurate information or we do not have access to your email address, we will not be responsible for failure to notify you. If any part of this Agreement is determined to be invalid or unenforceable under applicable law, that provision will be removed, and the remainder of the Agreement will continue to be valid and enforceable, except as expressly stated. Our failure to exercise or enforce any right or provision in this Agreement will not constitute a waiver of such right or provision. Except as otherwise required by law, the controlling language of this Agreement is English. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns. You and we acknowledge and agree that the Distribution Channel and its subsidiaries are intended third party beneficiaries of this Agreement and will have the right (and will be deemed to have accepted the right) to enforce this Agreement against you.</p>
<ol start=""14"">
<li><strong> Contact Information</strong></li>
</ol>
<p>You may contact Turnkey Estimates at:</p>
<p>Turnkey Estimates, LLC.</p>
<p><a href=""mailto:support@rightpathrealestate.com"">support@rightpathrealestate.com</a></p>
<p>If you have any questions, claims, or complaints, you should notify us through the contact or help feature of the relevant Service.</p>
<p>You hereby acknowledge that you have read and understood this Agreement and agree that by clicking ""Accept"" or by installing, copying, or using the Application you are acknowledging your agreement to be bound by this Agreement.</p>";

			eulaView.Source = htmlSource;
		}

		private async void Accept_OnClicked(object sender, EventArgs e)
		{
			Application.Current.Properties["eulaAccepted"] = true;

			await Navigation.PopModalAsync();
		}
	}
}

